### ISSUE TITLE
Change Home link on global header from blue to black

### ISSUE THREAD

**Issue by cydneycappello** [18F/State-TalentMAP#1751] opened 2018-04-12 14:44 UTC
Update Home link in global header to match design comps.

### Currently
Home is blue and bold. 
<img width="1023" alt="homepage-home-link-dev" src="https://user-images.githubusercontent.com/13770123/38684760-62294082-3e3e-11e8-840f-b70d81d70763.png">

### Desired
Home should be black and unbolded.

![homepage-home-link-edit](https://user-images.githubusercontent.com/13770123/38684774-6a68079c-3e3e-11e8-832c-c737cd709982.png)

**Comment by mjoyce91** [comment] 2018-04-13 13:08
Thanks @cydneycappello. Part of the original behavior was the the "currently navigated to" link would appear blue and bold. Do we want any type of behavior like that? It sort of doesn't make sense any more, because "Home" is the only internal link up there anymore.

**Comment by mjoyce91** [comment] 2018-04-18 15:55
Closed as expected behavior after discussion with @cydneycappello

**Closed by mjoyce91** 2018-04-18 15:55 UTC
Labels: Front End Dev, Visual Design
