### ISSUE TITLE
Bid Removal Bureau Concurrence

### ISSUE THREAD

**Issue by BrownCA5** [18F/State-TalentMAP#664] opened 2017-09-26 19:14 UTC
As a CDO
After written concurrence from the Bureau, I need a way  to remove a bid after the bidding deadline so that the bidder is no longer considered for the position.

## Acceptance Criteria
> An indication that the bid has been removed
> A copy of the concurrence between the Bureau and CDA

**Comment by burgwyn** [comment] 2017-09-27 17:40
Closing as a duplicate of #663

**Closed by burgwyn** 2017-09-27 17:40 UTC
