### ISSUE TITLE
Fix "method_complexity" issue in src/Components/ProfileDashboard/PositionInformation/PositionInformation.jsx

### ISSUE THREAD

**Issue by jseppi** [18F/State-TalentMAP#1310] opened 2018-01-29 15:33 UTC
Function `PositionInformation` has a Cognitive Complexity of 13 (exceeds 5 allowed). Consider refactoring.

https://codeclimate.com/github/18F/State-TalentMAP/src/Components/ProfileDashboard/PositionInformation/PositionInformation.jsx#issue_5a6f3a902b12380001000443

**Comment by mjoyce91** [comment] 2018-02-26 17:08
Duplicate of https://github.com/18F/State-TalentMAP/issues/1366

**Closed by mjoyce91** 2018-02-26 17:08 UTC
