### ISSUE TITLE
Homepage positions

### ISSUE THREAD

**Issue by krisdelacruz** [18F/State-TalentMAP#996] opened 2017-11-21 12:07 UTC
As a Bidder
I want the Homepage to display positions that I need
so that I can quickly see positions

## Acceptance Criteria
* Automates Skill code when user logs on

## Findings
Depending on their skill code users wanted to search on their specific skill code

## Recommendation
Enable to search by career track (skill code or skill code)

**Comment by wongperson** [comment] 2017-11-21 20:16
Closed. Duplicate of existing story #908

**Closed by wongperson** 2017-11-21 20:16 UTC
Labels: Phase 1 Testing, Ungroomed
