### ISSUE TITLE
Fix "method_complexity" issue in src/Components/PositionTitle/PositionTitle.jsx

### ISSUE THREAD

**Issue by jseppi** [18F/State-TalentMAP#1365] opened 2018-02-02 18:49 UTC
Function `render` has a Cognitive Complexity of 15 (exceeds 5 allowed). Consider refactoring.

https://codeclimate.com/github/18F/State-TalentMAP/src/Components/PositionTitle/PositionTitle.jsx#issue_5a74b23dc3bb440001000457

**Comment by burgwyn** [comment] 2018-02-27 15:00
Duplicate of #1309

**Closed by burgwyn** 2018-02-27 15:00 UTC
