### ISSUE TITLE
See Projected Vacancy

### ISSUE THREAD

**Issue by wongperson** [18F/State-TalentMAP#747] opened 2017-10-11 15:15 UTC
### Story
As a bidder,
I want to make sure I am able to view the Projected Vacancy,
So that I can predict the next move in the bidding process.

### Acceptance criteria
* When researching a position, I can see the projected vacancy date
* After a position is filled, a new projected vacancy is populated and visible

**Comment by esgoodman** [comment] 2017-10-11 17:30
This seems like more of a CDO story, @wongperson -- seems like the key thing for bidders is just whether this position is open for this bidding cycle or not?

**Comment by burgwyn** [comment] 2017-10-18 17:33
Duplicate of #758

**Closed by burgwyn** 2017-10-18 17:33 UTC
Labels: Epic, Ungroomed
