### ISSUE TITLE
CDO Portfolio Organization

### ISSUE THREAD

**Issue by wongperson** [18F/State-TalentMAP#884] opened 2017-11-01 04:30 UTC
As a CDO
I want an organized view of my clients 
so that I can visualize all of them at once

## Acceptance Criteria

**Comment by wongperson** [comment] 2017-11-01 14:46
Possible duplicate of CDO portfolio display and management.

**Comment by burgwyn** [comment] 2017-11-08 18:32
Closing as a duplicate of #806

**Closed by burgwyn** 2017-11-08 18:32 UTC
Labels: CDO - Leah, Roadmap - About my workforce quicker, Ungroomed
